Optional arg --branch for command 'list' which shows all branches in modules directories.

diff --git a/modman b/modman
--- a/modman
+++ b/modman
@@ -29,24 +29,24 @@ Module Manager (v$version)
 Global Commands:
   $script <command> [<options>]
 ------------------------------
-  init [basedir] [modmandir] initialize the pwd (or [basedir]) as the modman deploy root
-  list [--absolute]          list all valid modules that are currently checked out
-  status                     show VCS 'status' command for all modules
-  incoming                   show new VCS remote changesets for all VCS-based modules
-  update-all [modmandir]     update all modules that are currently checked out
-  deploy-all                 deploy all modules (no VCS interaction)
-  repair                     rebuild all modman-created symlinks (no updates performed)
-  clean                      clean up broken symlinks (run this after deleting a module)
-  automodman                 loops through module directory:
-                              - asks to include files & directories in new modman file
-                              - does not create symlinks
-  --help                     display this help message
-  --tutorial                 show a brief tutorial on using modman
-  --version                  display the modman script's version
-  [--force]                  overwrite existing files, ignore untrusted cert warnings
-  [--no-local]               skip processing of modman.local files
-  [--no-clean]               skip cleaning of broken symlinks
-  [--no-shell]               skip processing @shell lines
+  init [basedir] [modmandir]      initialize the pwd (or [basedir]) as the modman deploy root
+  list [--absolute] [--branch]    list all valid modules that are currently checked out (branch also shows active branch)
+  status                          show VCS 'status' command for all modules
+  incoming                        show new VCS remote changesets for all VCS-based modules
+  update-all [modmandir]          update all modules that are currently checked out
+  deploy-all                      deploy all modules (no VCS interaction)
+  repair                          rebuild all modman-created symlinks (no updates performed)
+  clean                           clean up broken symlinks (run this after deleting a module)
+  automodman                      loops through module directory:
+                                   - asks to include files & directories in new modman file
+                                   - does not create symlinks
+  --help                          display this help message
+  --tutorial                      show a brief tutorial on using modman
+  --version                       display the modman script's version
+  [--force]                       overwrite existing files, ignore untrusted cert warnings
+  [--no-local]                    skip processing of modman.local files
+  [--no-clean]                    skip cleaning of broken symlinks
+  [--no-shell]                    skip processing @shell lines
 
 Module Commands:
   $script <command> [<module>] [<options>] [[--] <VCS options>]
@@ -384,7 +384,7 @@ set_skipped ()
       echo "Module $module added to skip list."
     fi
   else
-    grep -v "^$module$" "$SKIP_FILE" > "$SKIP_FILE.tmp"; mv "$SKIP_FILE.tmp" "$SKIP_FILE" 
+    grep -v "^$module$" "$SKIP_FILE" > "$SKIP_FILE.tmp"; mv "$SKIP_FILE.tmp" "$SKIP_FILE"
     echo "Module $module removed from skip list."
   fi
 
@@ -611,7 +611,7 @@ apply_path ()
 # Automatically create a modman file
 run_automodman () #"$module" "$mm" "$wc_dir" "$wc_desc"
 {
-  # returns 0 on success 1 on error  
+  # returns 0 on success 1 on error
   amodule=$1
   amm=$2
   awc_dir=$3
@@ -621,13 +621,13 @@ run_automodman () #"$module" "$mm" "$wc_dir" "$wc_desc"
   #echo "in base directory $amm"
   #echo "in working copy $awc_dir"
   #echo "modman file will be or is $awc_desc"
-  
+
   #does the modman file exist?
   #yes
   if [ -r "$awc_desc" ]; then
     echo "$awc_desc file already exists"
     return 0 #exit without error
-    
+
   #no
   else
     #touch modman
@@ -638,7 +638,7 @@ run_automodman () #"$module" "$mm" "$wc_dir" "$wc_desc"
   declare -a incpaths
 
   for f in $(find $awc_dir \( ! -iname 'modman' ! -regex "$awc_dir.*/\..*" \)) #ignore hidden files and modman
-    do  
+    do
       #strip path down
       alngth=${#awc_dir} #length of working directory to remove from path
       alngth=$((alngth+1)) #increase by one to account for the fact we added a slash
@@ -650,22 +650,22 @@ run_automodman () #"$module" "$mm" "$wc_dir" "$wc_desc"
         prevmatch=0
         #todo: possibly there is a neater way to do this without a loop??
         for incPath in "${incpaths[@]}" #loop through incpaths
-        do  
+        do
           if [[ "$pathname" != "${pathname/$incPath/}" ]]; then
             prevmatch=1
           fi
         done
-        
-        #if substring then do recurse        
+
+        #if substring then do recurse
         if [[ $prevmatch -eq 0 ]]; then #make sure we have not previously matched
 
-          #pre-existing path: yes | no?      
+          #pre-existing path: yes | no?
           if grep -rq "^[^#].*\s$pathname$" "${amm}/"*"/modman" #target is what is important so find end line not beginning line
           then #pre-existing path: yes
             echo "..."
             echo "A path was found that exists in below modman description file" #error
             grep -r --color=always "\s$pathname$" "${amm}/"*"/modman"
-            echo "It is therefore presently illegal for it to be included in this module." 
+            echo "It is therefore presently illegal for it to be included in this module."
             echo "..."
             if [[ -d $f ]]; then
                     incpaths+=("$pathname")
@@ -677,15 +677,15 @@ run_automodman () #"$module" "$mm" "$wc_dir" "$wc_desc"
             if [[ "$include" == "" ]]; then
                  include="N"
             fi
-        
+
             if [ "$include" == "y" -o "$include" == "Y" ]; then #include path: yes
-          
+
               echo "..."
               echo "You answered y:yes modman will include the path"
               echo "..."
 
               #write path to modman
-              echo "$pathname  $pathname" >> $awc_desc #substring ${var:start} 
+              echo "$pathname  $pathname" >> $awc_desc #substring ${var:start}
               #was it a directory or file
               if [[ -d $f ]]; then
                   incpaths+=("$pathname")
@@ -694,9 +694,9 @@ run_automodman () #"$module" "$mm" "$wc_dir" "$wc_desc"
             elif [ "$include" == "n" -o "$include" == "N" ]; then #include path: no
               echo "You answered N:no, modman is not including the path"
             else
-              echo "Warning: you answered $include which is invalid, modman is not including path"  
-            fi    
-        
+              echo "Warning: you answered $include which is invalid, modman is not including path"
+            fi
+
           fi # test other modules for pre-existing path
         fi # test prvious match
       fi #continue
@@ -777,11 +777,27 @@ fi
 # Handle "list" command
 if [ "$action" = "list" ]; then
   prefix=''
-  if [ "$1" = "--absolute" ]; then shift; prefix="$mm/"; fi
-  if [ -n "$1" ]; then echo "Too many arguments to list command."; exit 1; fi
+  if [ "$1" = "--absolute" ] || [ "$2" == "--absolute" ]; then
+    prefix="$mm/";
+  fi
+  if [ -n "$3" ]; then echo "Too many arguments to list command."; exit 1; fi
   for module in $(ls -1 "$mm"); do
     if [ -d "$mm/$module" -a -e "$mm/$module/modman" ]; then
-      echo "${prefix}$module"
+      if [ "$1" = "--branch" ] || [ "$2" == "--branch" ]; then
+        echo -e "--- $(bold)${prefix}$module$(unbold) ---"
+        if [ -d "$mm/$module/.git" ]; then
+          cd "$mm/$module" && git branch
+          echo
+        elif [ -d "$mm/$module/.svn" ]; then
+          cd "$mm/$module" && svn info
+          echo
+        elif [ -d "$mm/$module/.hg" ]; then
+          cd "$mm/$module" && hg branch info
+          echo
+        fi
+      else
+        echo "${prefix}$module"
+      fi
     fi
   done
   exit 0
